### ISSUE TITLE
header 로그인, 로그아웃

### ISSUE THREAD

**Issue by whansoo** [team-project7/KDT4-M4public#22]
header 부분에 있는 로그인, 로그아웃 

1. header에 있는 로그인을 클릭 하면 login 페이지로 이동합니다
2. 로그인을 하면 localstrage에 token과 email등을 저장 후 main 페이지로 이동합니다
3. 메인페이지로 이동 후 로그인이였던 글자는 로그아웃으로 보여줍니다. 
4. 새로고침이나 다른 페이지로 이동하여도 로그인을 유지합니다.
5. 로그아웃을 하면 응답을 true로 반환하고 다시 login페이지로 이동합니다

참고사항
a태그를 사용하는데 자동으로 새로고침 되는 것을 알게 되었다. react에서는 Link to를 사용하는데 이것은 새로고침이 되지 않는다
그래서 Link to를 사용하는가 보다.
처음에 로그아웃을 하기 위해 getiem으로 token을 받아와서 logout으로 보내주는데 느낌이 이상했다. 그래서 request파일에서 logout부분에 콘솔을 찍어 봤는데 역시나 반응이 없었다 그래서 원인을 찾아보니 a 링크에서 새로고침이 되서 token값을 넘겨주지 못하는 것이였다 그래서 a 링크에 href="" 이것을 지워주니 새로고침이 되지 않았다..
다음에는 어떠한 데이터를 넘겨 줄 때 a 링크를 사용 하는 것보다 다른 방법을 사용하거나 click 했을때 그 함수안에 데이터를 넣어주는 방식으로 사용 해야 할 것 같다...

**Comment by jyc-coder** [comment]
그래서 로그아웃 버튼에 addEventListener 를 부여해서 location.replace를 사용해서 이전으로 돌아갈수 없게 설정하는제 좋다고 생각했습니다. 고생했어요!

**Comment by whansoo** [comment]
아하 그렇군요 과제 하면서 많은걸 배우는 것 같습니다..
