### ISSUE TITLE
Footer Module ~ 2월 9일

### ISSUE THREAD

**Issue by sung34** [team-project7/KDT4-M4public#3]
[Kream](https://www.kream.co.kr) 홈페이지 Footer 부분을 담당합니다. 

# HTML 
- 사이트 내의 컨텐츠를 클론하여 사용합니다.
# JS
- footer 내의 a 태그 href는 구현하지 않습니다. 

# CSS

- 화면 너비 
  - 모바일 max-width: 768px
  - md max-width: 960px
  - lg max-width: 960px ~ max-width: 나머지

**Comment by sung34** [comment]
lg PC환경 구현 완료
프로젝트 일정에 따라 768px, 960px 너비 반응형 구현 대기

**Comment by jyc-coder** [comment]
고생했습니다!
